Merge from main (#91)
* fix: Modify retention policy of influxdb (#81)

* fix: Modify retention policy of influxdb

* fix: Update cq Interface-check-command

* no-ci: Update BNGBlaster image version to v2.0.29

* no-ci: Update BNGBlaster image version to v2.0.30

* no-ci: Update BNGBlaster image version to v2.0.31

* no-ci: Update BNGBlaster image version to v2.0.32

* no-ci: Update BNGBlaster image version to v2.0.33

* fix: command option for force rebalance in icinga2_rebalance.py script (#87)

* Fix/ci release (#89)

* fix: release on main

* fix: handle case cannot get committer info

* fix: syntax

* fix: add echo to debug

* fix: add commit link

* no-ci: Release

* no-ci: Release

* no-ci: Update preparation image version to v1.4.4

* no-ci: Update BNGBlaster image version to v2.0.34

* fix: modify mail content and fix mail condition (#90)

* fix: modify mail content and fix mail condition

* fix: add success mail

* fix: add success mail

* fix: syntax

* fix: syntax

---------

Co-authored-by: svtechnmaa <nmaa@svtech.com.vn>
Co-authored-by: peihneyugn <46918746+vyvuvivo@users.noreply.github.com>
Co-authored-by: izme <phamtranlinhchi02@gmail.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -583,7 +583,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           persist-credentials: false
-          ref: ${{ env.COMMIT_FULL_ID }}
+          ref: main
           path: charts
           token: ${{ secrets.PUSH_TOKEN }}
 
@@ -631,7 +631,6 @@ jobs:
           cd ${{ github.workspace }}/charts
           git remote set-url origin https://svtechnmaa:${{ secrets.PUSH_TOKEN }}@github.com/svtechnmaa/charts.git
           git fetch origin main
-          git checkout main
           git config --global user.name "svtechnmaa"
           git config --global user.email "nmaa@svtech.com.vn"
           git config --global commit.gpgSign true
@@ -655,26 +654,42 @@ jobs:
     if: always() && !cancelled() && needs.check_charts.outputs.no_ci != 'true' && needs.create_vm.result == 'success' && ( needs.check_charts.outputs.check_nmaa == 'true' || needs.check_charts.outputs.check_elk == 'true') 
     steps:
       - name: Checkout code
-        if: needs.test_elk.result != 'success' || needs.test_nmaa.result != 'success'      
         uses: actions/checkout@v4
         with:
           ref: ${{ env.COMMIT_FULL_ID }}
 
       - name: Get Commit ID and Committer Info
-        if: needs.test_elk.result != 'success' || needs.test_nmaa.result != 'success'
         run: |
           COMMIT_ID=${{ env.COMMIT_FULL_ID }}
+
+          # Get committer info
+          echo "Getting committer info for commit ID: $COMMIT_ID"
           COMMITTER_EMAIL=$(git show -s --format='%ce' $COMMIT_ID)
           COMMITTER_NAME=$(git show -s --format='%cn' $COMMIT_ID)
-          if [ "$COMMITTER_NAME" = "GitHub" ]; then
-            COMMITTER_NAME="committers"
+
+          # Get author info if committer email is noreply
+          if [[ "$COMMITTER_EMAIL" == *noreply* ]]; then 
+            echo "Committer email is noreply, getting author info..."
+            COMMITTER_NAME=$(git show -s --format='%an' $COMMIT_ID)
+            COMMITTER_EMAIL=$(git show -s --format='%ae' $COMMIT_ID)
           fi
+
+          # Fallback to github event info if still noreply
+          if [[ "$COMMITTER_EMAIL" == *noreply* ]]; then 
+            echo "Committer email is still noreply, using github event info..."
+            COMMITTER_NAME=${{ github.event.pusher.name || github.event.sender.login }}
+            COMMITTER_EMAIL=${{ github.event.pusher.email}}
+          fi
+
           echo "COMMIT_ID=${COMMIT_ID}" >> $GITHUB_ENV
-          echo "COMMITTER_EMAIL=${COMMITTER_EMAIL}" >> $GITHUB_ENV
           echo "COMMITTER_NAME=${COMMITTER_NAME}" >> $GITHUB_ENV
+          echo "COMMITTER_EMAIL=${COMMITTER_EMAIL}" >> $GITHUB_ENV
+          echo "COMMIT_ID: $COMMIT_ID"
+          echo "COMMITTER_NAME: $COMMITTER_NAME"
+          echo "COMMITTER_EMAIL: $COMMITTER_EMAIL"
         
-      - name: Send mail to committer
-        if: needs.test_elk.result != 'success' || needs.test_nmaa.result != 'success'
+      - name: Send mail to committer to notify failure
+        if: (needs.check_charts.outputs.check_elk == 'true' && needs.test_elk.result != 'success') || (needs.check_charts.outputs.check_nmaa == 'true' && needs.test_nmaa.result != 'success')
         continue-on-error: true
         uses: dawidd6/action-send-mail@v6
         with:
@@ -683,22 +698,29 @@ jobs:
           secure: true
           username: ${{ vars.MAIL_USERNAME }}
           password: ${{ secrets.MAIL_PASSWORD }}
-          subject: "[SVTECH GITHUB] Workflow #${{ github.run_number }} from repo ${{ github.repository }} failed!"
-          body: |
-            Hi ${{ env.COMMITTER_NAME }},
-            The workflow #${{ github.run_number }} from repo ${{ github.repository }} has failed.
-            After the failure, the workflow will wait for ${{ env.WAIT_SECONDS }}s before cleaning up the environment.
+          subject: "[SVTECH GITHUB] Run failed: Workflow #${{ github.run_number }} from repo ${{ github.repository }}"
+          html_body: |
+            <p>Hi ${{ env.COMMITTER_NAME || 'contributors' }},</p>
             
-            Please check the details and take appropriate action at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+            <p>The workflow #${{ github.run_number }} that run commit <a href="${{ github.server_url }}/${{ github.repository }}/commit/${{ env.COMMIT_FULL_ID }}">#${{ env.COMMIT_ID }}</a> from repo ${{ github.repository }} has failed.</p>
             
-            Best regards,
+            <p>
+              After the failure, the workflow will wait for ${{ env.WAIT_SECONDS }}s before cleaning up the environment.<br />
+              Please check the workflow details and take appropriate action at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+            </p>
+            
+            <p>For more information, please contact the SRE team.</p>
+            
+            <p>
+            Best regards,<br />
             SRE Team
+            </p>
           to: ${{ env.COMMITTER_EMAIL }},${{ vars.DEFAULT_MAIL_RECIPIENTS }}
           from: ${{ vars.MAIL_USERNAME }}
 
 
       - name: Wait before cleanup
-        if: needs.test_elk.result != 'success' || needs.test_nmaa.result != 'success'
+        if: (needs.check_charts.outputs.check_elk == 'true' && needs.test_elk.result != 'success') || (needs.check_charts.outputs.check_nmaa == 'true' && needs.test_nmaa.result != 'success')
         continue-on-error: true
         run: |
           if [ ${{ env.WAIT_SECONDS }} -gt 3600 ]; then
@@ -715,6 +737,33 @@ jobs:
           token: ${{ secrets.PUSH_TOKEN }}
           path: SVTECH_CICD_Utilities
           ref: ${{ env.CICD_UTILITIES_BRANCH }}
+
+      - name: Send mail to committer to notify success
+        if: ${{ ! ( (needs.check_charts.outputs.check_elk == 'true' && needs.test_elk.result != 'success') || (needs.check_charts.outputs.check_nmaa == 'true' && needs.test_nmaa.result != 'success') ) }}
+        continue-on-error: true
+        uses: dawidd6/action-send-mail@v6
+        with:
+          server_address: smtp.gmail.com
+          server_port: 465
+          secure: true
+          username: ${{ vars.MAIL_USERNAME }}
+          password: ${{ secrets.MAIL_PASSWORD }}
+          subject: "[SVTECH GITHUB] Run succeeded: Workflow #${{ github.run_number }} from repo ${{ github.repository }}"
+          html_body: |
+            <p>Hi ${{ env.COMMITTER_NAME || 'contributors' }},</p>
+            
+            <p>
+              The workflow #${{ github.run_number }} that run commit <a href="${{ github.server_url }}/${{ github.repository }}/commit/${{ env.COMMIT_FULL_ID }}">#${{ env.COMMIT_ID }}</a> from repo ${{ github.repository }} has succeeded.<br />
+              For more details, please visit this workflow link: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+            </p>
+                        
+            <p>
+            Best regards,<br />
+            SRE Team
+            </p>
+          to: ${{ env.COMMITTER_EMAIL }},${{ vars.DEFAULT_MAIL_RECIPIENTS }}
+          from: ${{ vars.MAIL_USERNAME }}
+        
 
       - name: Download build_vars artifact
         uses: actions/download-artifact@v4
